DELETE FROM `stock` WHERE `store_id`='0';
DELETE FROM `stock_position` WHERE `store_id`='0';
INSERT INTO `stock` (`stock_id`, `stock_code`, `stock_name`,`store_id`, `stock_count`) VALUES(1,'MLK-001','PEAK SMALL','0',0),(2,'MLK-002','PEAK BIG','0',0),(3,'MLK-003','COWBELL SMALL','0',0),(4,'MLK-004','COWBELL BIG','0',0),(5,'MLK-005','COAST BIG','0',0),(6,'NDL-001','INDOMIE','0',0),(7,'NDL-002','O NOODLES','0',0),(8,'SGR-001','DANGOTE SUGAR','0',0),(9,'SGR-002','STLOUIS','0',0),(10,'BVG-001','MILO SMALL','0',0),(11,'BVG-002','MILO BIG','0',0),(12,'BVG-003','BOURNVITA SMALL','0',0),(13,'BVG-004','BOURNVITA BIG','0',0),(14,'BVG-005','OVALTINE SMALL','0',0),(15,'BVG-006','OVALTINE BIG','0',0),(16,'JUI-001','CHIVITA','0',0),(17,'JUI-002','FUMAN','0',0),(18,'JUI-003','CERES','0',0),(19,'SPG-001','DANGOTE SPAGHETTI','0',0),(20,'SPG-002','GOLDEN PENNY SPAGHETTI','0',0);
INSERT INTO `stock_position` ( `stock_id`, `store_id`, `unit`, `stock_count`) VALUES(1,'0',1,0),(2,'0',1,0),(3,'0',1,0),(4,'0',1,0),(5,'0',1,0),(6,'0',1,0),(7,'0',1,0),(8,'0',1,0),(9,'0',1,0),(10,'0',1,0),(11,'0',1,0),(12,'0',1,0),(13,'0',1,0),(14,'0',1,0),(15,'0',1,0),(16,'0',1,0),(17,'0',1,0),(18,'0',1,0),(19,'0',1,0),(20,'0',1,0);
UPDATE `stock` SET `stock`.`stock_count`=233904 WHERE `stock`.`store_id`='0' AND `stock`.`stock_id`='1';
UPDATE `stock` SET `stock`.`stock_count`=2176523 WHERE `stock`.`store_id`='0' AND `stock`.`stock_id`='2';
UPDATE `stock` SET `stock`.`stock_count`=32715 WHERE `stock`.`store_id`='0' AND `stock`.`stock_id`='3';
UPDATE `stock` SET `stock`.`stock_count`=36576559 WHERE `stock`.`store_id`='0' AND `stock`.`stock_id`='4';
UPDATE `stock` SET `stock`.`stock_count`=244879 WHERE `stock`.`store_id`='0' AND `stock`.`stock_id`='5';
UPDATE `stock` SET `stock`.`stock_count`=34370 WHERE `stock`.`store_id`='0' AND `stock`.`stock_id`='6';
UPDATE `stock` SET `stock`.`stock_count`=258104 WHERE `stock`.`store_id`='0' AND `stock`.`stock_id`='7';
UPDATE `stock` SET `stock`.`stock_count`=75525 WHERE `stock`.`store_id`='0' AND `stock`.`stock_id`='8';
UPDATE `stock` SET `stock`.`stock_count`=2175724 WHERE `stock`.`store_id`='0' AND `stock`.`stock_id`='9';
UPDATE `stock` SET `stock`.`stock_count`=21369269 WHERE `stock`.`store_id`='0' AND `stock`.`stock_id`='10';
UPDATE `stock` SET `stock`.`stock_count`=39479 WHERE `stock`.`store_id`='0' AND `stock`.`stock_id`='11';
UPDATE `stock` SET `stock`.`stock_count`=2147 WHERE `stock`.`store_id`='0' AND `stock`.`stock_id`='12';
UPDATE `stock` SET `stock`.`stock_count`=7236 WHERE `stock`.`store_id`='0' AND `stock`.`stock_id`='13';
UPDATE `stock` SET `stock`.`stock_count`=12508 WHERE `stock`.`store_id`='0' AND `stock`.`stock_id`='14';
UPDATE `stock` SET `stock`.`stock_count`=2147702463 WHERE `stock`.`store_id`='0' AND `stock`.`stock_id`='15';
UPDATE `stock` SET `stock`.`stock_count`=22844 WHERE `stock`.`store_id`='0' AND `stock`.`stock_id`='16';
UPDATE `stock` SET `stock`.`stock_count`=12328 WHERE `stock`.`store_id`='0' AND `stock`.`stock_id`='17';
UPDATE `stock` SET `stock`.`stock_count`=243415 WHERE `stock`.`store_id`='0' AND `stock`.`stock_id`='18';
UPDATE `stock` SET `stock`.`stock_count`=89290 WHERE `stock`.`store_id`='0' AND `stock`.`stock_id`='19';
UPDATE `stock` SET `stock`.`stock_count`=66935 WHERE `stock`.`store_id`='0' AND `stock`.`stock_id`='20';
UPDATE `stock_position` SET `stock_position`.`stock_count`=233904 WHERE `stock_position`.`store_id`='0' AND `stock_position`.`stock_id`='1';
UPDATE `stock_position` SET `stock_position`.`stock_count`=2176523 WHERE `stock_position`.`store_id`='0' AND `stock_position`.`stock_id`='2';
UPDATE `stock_position` SET `stock_position`.`stock_count`=32715 WHERE `stock_position`.`store_id`='0' AND `stock_position`.`stock_id`='3';
UPDATE `stock_position` SET `stock_position`.`stock_count`=36576559 WHERE `stock_position`.`store_id`='0' AND `stock_position`.`stock_id`='4';
UPDATE `stock_position` SET `stock_position`.`stock_count`=244879 WHERE `stock_position`.`store_id`='0' AND `stock_position`.`stock_id`='5';
UPDATE `stock_position` SET `stock_position`.`stock_count`=34370 WHERE `stock_position`.`store_id`='0' AND `stock_position`.`stock_id`='6';
UPDATE `stock_position` SET `stock_position`.`stock_count`=258104 WHERE `stock_position`.`store_id`='0' AND `stock_position`.`stock_id`='7';
UPDATE `stock_position` SET `stock_position`.`stock_count`=75525 WHERE `stock_position`.`store_id`='0' AND `stock_position`.`stock_id`='8';
UPDATE `stock_position` SET `stock_position`.`stock_count`=2175724 WHERE `stock_position`.`store_id`='0' AND `stock_position`.`stock_id`='9';
UPDATE `stock_position` SET `stock_position`.`stock_count`=21369269 WHERE `stock_position`.`store_id`='0' AND `stock_position`.`stock_id`='10';
UPDATE `stock_position` SET `stock_position`.`stock_count`=39479 WHERE `stock_position`.`store_id`='0' AND `stock_position`.`stock_id`='11';
UPDATE `stock_position` SET `stock_position`.`stock_count`=2147 WHERE `stock_position`.`store_id`='0' AND `stock_position`.`stock_id`='12';
UPDATE `stock_position` SET `stock_position`.`stock_count`=7236 WHERE `stock_position`.`store_id`='0' AND `stock_position`.`stock_id`='13';
UPDATE `stock_position` SET `stock_position`.`stock_count`=12508 WHERE `stock_position`.`store_id`='0' AND `stock_position`.`stock_id`='14';
UPDATE `stock_position` SET `stock_position`.`stock_count`=2147702463 WHERE `stock_position`.`store_id`='0' AND `stock_position`.`stock_id`='15';
UPDATE `stock_position` SET `stock_position`.`stock_count`=22844 WHERE `stock_position`.`store_id`='0' AND `stock_position`.`stock_id`='16';
UPDATE `stock_position` SET `stock_position`.`stock_count`=12328 WHERE `stock_position`.`store_id`='0' AND `stock_position`.`stock_id`='17';
UPDATE `stock_position` SET `stock_position`.`stock_count`=243415 WHERE `stock_position`.`store_id`='0' AND `stock_position`.`stock_id`='18';
UPDATE `stock_position` SET `stock_position`.`stock_count`=89290 WHERE `stock_position`.`store_id`='0' AND `stock_position`.`stock_id`='19';
UPDATE `stock_position` SET `stock_position`.`stock_count`=66935 WHERE `stock_position`.`store_id`='0' AND `stock_position`.`stock_id`='20';
INSERT INTO `store_daily_summary` ( `store_id`, `opening_balance`, `total_cash_in`, `total_cash_out`, `total_credit_sales`, `closing_balance`, `date`,  `time`) VALUES('0',0,0,0,0,0,'2016-03-01','09:15:04');