INSERT INTO `cashstock` (`cashstock_id`, `particulars`, `remark`, `amount`, `date`, `store_name`) VALUES(127,'bassey','',1523019.00,'2016-02-22','Dynamix'),(128,'bassey','',1532604.00,'2016-02-22','Dynamix'),(129,'Opening Balance','',234567.00,'2016-02-22','Dynamix'),(130,'bisi','',4412.00,'2016-02-22','Dynamix');
DELETE FROM `stock` WHERE `store_name`='Dynamix';
DELETE FROM `stock_position` WHERE `store_name`='Dynamix';
INSERT INTO `stock` (`stock_id`, `stock_code`, `stock_name`,`store_name`, `stock_count`) VALUES(1,'PROV-200','rice','Dynamix',0),(9,'SUG-2749','dangote sugar','Dynamix',0),(11,'ONS-111','Titus Sardine','Dynamix',0),(13,'PROV-50','Laser Oil','Dynamix',0),(14,'ONS-023','Nothern fresh onions','Dynamix',0),(15,'PROV-25','Dangote Spagetti','Dynamix',0);
INSERT INTO `stock_position` ( `stock_id`, `store_name`, `unit`, `stock_count`) VALUES(1,'Dynamix',1,0),(9,'Dynamix',1,0),(11,'Dynamix',1,0),(13,'Dynamix',1,0),(14,'Dynamix',1,0),(15,'Dynamix',1,0);
INSERT INTO `sales_invoice_daily` (`sales_date`, `sales_time`, `purchase_amount`, `store_name`, `payment_type`, `status`, `cashier`, `store_confirmation`, `operator`, `customer`, `invoice_num`) VALUES('2016-02-22','10:38:05',4412.00,'Dynamix','CASH','CLOSED','','NOT SUPPLIED','charles','bisi',628);
UPDATE `stock` SET `stock`.`stock_count`=2342392 WHERE `stock`.`store_name`='Dynamix' AND `stock`.`stock_id`='1';
UPDATE `stock` SET `stock`.`stock_count`=3435869 WHERE `stock`.`store_name`='Dynamix' AND `stock`.`stock_id`='9';
UPDATE `stock` SET `stock`.`stock_count`=55909006 WHERE `stock`.`store_name`='Dynamix' AND `stock`.`stock_id`='11';
UPDATE `stock` SET `stock`.`stock_count`=342820 WHERE `stock`.`store_name`='Dynamix' AND `stock`.`stock_id`='13';
UPDATE `stock` SET `stock`.`stock_count`=346159 WHERE `stock`.`store_name`='Dynamix' AND `stock`.`stock_id`='14';
UPDATE `stock` SET `stock`.`stock_count`=2178211 WHERE `stock`.`store_name`='Dynamix' AND `stock`.`stock_id`='15';
UPDATE `stock_position` SET `stock_position`.`stock_count`=2342392 WHERE `stock_position`.`store_name`='Dynamix' AND `stock_position`.`stock_id`='1';
UPDATE `stock_position` SET `stock_position`.`stock_count`=3435869 WHERE `stock_position`.`store_name`='Dynamix' AND `stock_position`.`stock_id`='9';
UPDATE `stock_position` SET `stock_position`.`stock_count`=55909006 WHERE `stock_position`.`store_name`='Dynamix' AND `stock_position`.`stock_id`='11';
UPDATE `stock_position` SET `stock_position`.`stock_count`=342820 WHERE `stock_position`.`store_name`='Dynamix' AND `stock_position`.`stock_id`='13';
UPDATE `stock_position` SET `stock_position`.`stock_count`=346159 WHERE `stock_position`.`store_name`='Dynamix' AND `stock_position`.`stock_id`='14';
UPDATE `stock_position` SET `stock_position`.`stock_count`=2178211 WHERE `stock_position`.`store_name`='Dynamix' AND `stock_position`.`stock_id`='15';
INSERT INTO `store_daily_summary` ( `store_name`, `opening_balance`, `total_cash_in`, `total_cash_out`, `total_credit_sales`, `closing_balance`, `date`,  `time`) VALUES('Dynamix',234567.00,3294602.00,0,0,3529169,'2016-02-22','06:55:49');